### ISSUE TITLE
WIN10点击显示二维码软件直接报错

### ISSUE THREAD

**Issue by peterrosetu** [TonyChen56/WeChatRobot#1]

**Comment by TonyChen56** [comment]
取二维码数据方式不当 下个版本修复

**Comment by likansky** [comment]
我也是一样

**Comment by TonyChen56** [comment]
显示二维码根本原因 是由于环境问题而导致dll注入失败 安装VS2017 勾选使用C++桌面开发 即可解决

**Comment by lorki** [comment]
Please install the corresponding pre-software. You can download them [**here**](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).
