### ISSUE TITLE
同时接收多条消息时会有消息丢失

### ISSUE THREAD

**Issue by LeLe86** [TonyChen56/WeChatRobot#11]
聊天消息和公众号推送一起收到时会出现聊天消息没抓到，只显示了一条公众号消息的情况。
如果不发聊天消息，只开着软件接收公众号消息，会出现如果短时间内来了多个公众号的消息，会只能抓到一条。
麻烦作者看一下，谢谢。

**Comment by TonyChen56** [comment]
本项目只用于技术研究 不对任何其他用途负责

**Comment by LeLe86** [comment]
啥？

**Comment by lorki** [comment]
emmm.......I always think that as a normal user, the current message processing efficiency should be no problem.

**Comment by LeLe86** [comment]
> emmm.......I always think that as a normal user, the current message processing efficiency should be no problem.

A：为什么每次去商店买30个苹果，回到家之后只有20个了呢？
B：我觉得20个也够了，你不应该纠结这个问题，你为什么会这么贪婪想要30个呢？我给你带苹果回来就已经是对你很好了，我只负责带，不负责听你抱怨。
过了几天，B 的钱包、钥匙、手机丢了，检查过后发现因为他装东西的袋子上破了一个洞。

**Comment by LeLe86** [comment]
> emmm.......I always think that as a normal user, the current message processing efficiency should be no problem.

A：为什么每次去商店买30个苹果，回到家之后只有20个了呢？
B：我觉得20个也够了，你不应该纠结这个问题，你为什么会这么贪婪想要30个呢？我给你带苹果回来就已经是对你很好了，我只负责运输，不对任何其他事情负责。
过了几天，B 的钱包、钥匙、手机丢了，检查过后发现因为他装东西的袋子上破了一个洞。

**Comment by lorki** [comment]
中文回复：如果你想更完整的功能可以考虑买我的API服务。直接是协议支撑。不存在这些毛病且功能更多。请不要指责说我们开发不负责，毕竟这个项目我们没收一分钱。我们有多少时间来免费做公益？有几个人给过我们赞助？实话实，连句谢谢都没有。脸红不脸红？

**Comment by LeLe86** [comment]
首先，我用中文提问，你搞个洋文回复，而你又不是作者的 ID ，我以为你是个路人甲，那我对你的答案不满意的情况下回复一下我的看法没问题吧？

如果是作者回复的话我会客气点，拿人手短的道理我还是懂的。

说实话，”谢谢“ 我说了，所以我脸不红。反倒是你睁大眼说瞎话脸红不红？

不过我现在还可以再跟你说一声谢谢，万一你的意思是我要单独跟你说声谢谢呢。

我提出了一个遇到的问题，而这个问题有可能是潜在bug，它至少是个中性的交流问题吧，你怎么说得我像是个要求你免费修复的伸手党？我可从没有强迫作者一定要去做修改，现在既然作者的意思是”我知道这个问题，但我不打算解决了，你自己研究吧“，没问题，我完全理解。

但如果一个路人甲说”我觉得丢消息没关系，一般人使用足够了“ 那在我看来就是来了一个和稀泥的。
但即便如此，我没有指责你，只是由你的话想到了一个小故事，故事中用了你的原话，至于你怎么解读那是你的事了，你会怎么想就会怎么去解读喽。

至于你说的买API，做公益，赞助，关我啥事？你撒气撒错地方了吧？

提个建议啊：又想对别人撒气发泄不满，又想让别人买你收费服务，你当别人都是任你揉捏的软柿子吗？

最后，提个建议：你的文章、思路大量借鉴了 Hezone 在网易课堂上的收费课程里的内容，而你又这么讲究要感谢别人，那你的项目和文章里是不是也应该提一下人家的名字表示感谢呢？

**Comment by LeLe86** [comment]
不小心把我的上一条回复删了。那我只回复3点明显的，其他有的没的我就不扯了。
1、我说”谢谢“了，我脸不红。倒是你睁眼说瞎话脸红不红？
2、你不是作者的ID，故意用洋文回复一个中文问题，在我看来是个装x的路人甲，而且你对我提的问题是在和稀泥，我并不满意，所以编了一个小故事回复你。我可从没说过作者必须要解决这个问题，也没要求你免费做公益，别给我扣这么大一个帽子。
3、你的文章、源代码的思路大量借鉴了 Hezone 在网易课堂上的收费课程里的内容，而你又这么讲究要感谢别人，那你的项目和文章里是不是也应该提一下人家的名字表示感谢呢？

**Comment by justtsuj** [comment]
你好，你解决上述问题了吗？ @LeLe86
