### ISSUE TITLE
哪位朋友那边有2.6.8.52的安装包？

### ISSUE THREAD

**Issue by HarrisHan** [TonyChen56/WeChatRobot#12]

**Comment by TonyChen56** [comment]
链接：https://pan.baidu.com/s/1kZTBDPHNSSbyC1tVP-Lj8g 
提取码：d9oj

**Comment by lorki** [comment]
I have submitted this version of the installation package . You can download it [**here**](https://github.com/TonyChen56/WeChatRobot/raw/dev/WeChatInstallPack/WeChatSetup_2.6.8.52.exe)

**Comment by HarrisHan** [comment]
> 链接：https://pan.baidu.com/s/1kZTBDPHNSSbyC1tVP-Lj8g
> 提取码：d9oj

Six six six

**Comment by HarrisHan** [comment]
> I have submitted this version of the installation package . You can download it [**here**](https://github.com/TonyChen56/WeChatRobot/raw/dev/WeChatInstallPack/WeChatSetup_2.6.8.52.exe)

Six six six

**Comment by codeByDog** [comment]
新版本开源地址： [https://github.com/codeByDog/pcWechat](url) （将持续不断更新，且用不收费）
![鬼手不要脸](https://user-images.githubusercontent.com/49958949/70022221-6cbd1a00-15ce-11ea-9021-d3d09aad0ae8.png)
