### ISSUE TITLE
关于解密数据库

### ISSUE THREAD

**Issue by 459217974** [TonyChen56/WeChatRobot#14]
是否可以完全备份手机上的聊天记录，包括图片语音等信息。
我想做一个项目将自己的聊天自己存到云端，手机快装不下了。
目前只找到从IOS备份文件提取聊天记录的方法，不知道你这个是否可以。
望解惑，谢谢~

**Comment by lorki** [comment]
In subsequent development versions, **WebSocket** or **HTTP REST** API interfaces will be provided. You can use them to store data in real time elsewhere.

**Comment by 459217974** [comment]
微信不支持多端同时登录，我并不想在服务器上一直登录我的微信并存储消息，这种方案已经有很多方法可以实现了，我需要的是把手机上的聊天记录定期备份到服务器以便可以随时查询，因为手机上的聊天记录永远是最全面的，但是手机容量有限，我需要把聊天记录存到服务器。

发自我的 iPhone

**Comment by lorki** [comment]
In this case...If you just need to back up your data, I suggest you **use iCloud**.

**Comment by TonyChen56** [comment]
你需不需要是你的事情 我这个项目源码已经放出来了 没有赚你一分钱 我为什么要花时间去完成你的需求？你没资格跟我提需求

**Comment by 459217974** [comment]
@TonyChen56  这样说吧  我只是想知道通过这个项目的解密数据库功能是不是可以完全解密出微信聊天记录  至于我说的那些需求我并不是提给你的  是我自己要做的   我有我的需求  但是我不会破解相关的技术   每个人擅长的领域都不同  你擅长逆向破解  你研究出怎么解密微信  所以你开源出来  分享喜悦也好 炫耀也好 (如果你的目的是贡献开源社区, 那更应该为你的项目负责)  既然分享出来了  大家咨询一下也没什么吧   干嘛上来就怼   如果你不想理任何人的问题 你大可以关闭 issue 功能  或者就放在那里不理也行

@lorki 谢谢你一直给我提供解决方案, 但是你的方案对于我都不是很合适, 如果你也了解这个项目的解密相关的原理的话, 希望你能帮助我解密微信聊天记录, 其他的事我会自己实现, 我也准备开源出去, 我觉得会有一些人需要, 其实我想实现的是微信聊天记录漫游功能, 就像QQ会员有的那个功能.

**Comment by lorki** [comment]
The **difficulty** lies in the **iPhone's application isolation**, which makes it impossible to read the corresponding data files under normal circumstances. If it's **Android**, it's much simpler, and some open source projects have **already decrypted** it.If you want to solve your problem better, I suggest you look at those projects.and finally thx for your interest in our project.

**Comment by lorki** [comment]
But now I have a way to **bypass isolation** and achieve the **real-time backup** you want. If you are interested, you can **contact me for more details**.

**Comment by 459217974** [comment]
@lorki 不知道你说的方法是不是用 iTunes 全量备份手机，然后从备份文件里找出聊天记录，这个方法我已经尝试过了，完全可以解决我的需求，唯一的缺点就是全量备份一次手机非常慢，至少要半个小时以上，我关注这个项目的初衷是我注意到微信 PC 版可以备份和恢复手机上的聊天记录，备份之后的文件其实也是一个加密的 sqlite 数据库，所以我想直接解密那个数据库的文件获取聊天记录，微信 PC 版备份手机聊天记录相比全量备份手机要快的多，另外，前一个方法只有 iOS 用户可以使用，我想提供一个通用的解决方案。安卓手机上的聊天记录我目前找到的方案都是需要 root 手机的，并不适合所有人。

下面我说一下我目前的构思：
1. 备份微信聊天记录，至少包括图片，语音，表情包。
2. 将聊天记录存入 ElasticSearch，开放搜索接口。某些场景可能还需要结合一下 MySQL数据库。
3. 写一个微信小程序，方便在微信随时查找聊天记录。
4. 鉴权可以直接采用绑定自己微信号的方案，防止聊天记录泄露。
5. 简化部署步骤加编写详细部署方案，方便大家各自实现聊天记录漫游功能。

如果可以的话，你可以给我一个联系方式，咱们讨论一下，我的用户名是我的QQ，邮箱也可以。
