### ISSUE TITLE
老哥，你的桌面很有意思啊，分享一下哈

### ISSUE THREAD

**Issue by Gui-qLi** [TonyChen56/WeChatRobot#15]

**Comment by TonyChen56** [comment]
链接：https://pan.baidu.com/s/1VIqSSvGxbFOEyX8tPs1xQA 
提取码：80wd 
拿走不谢！

**Comment by lyh2606179909** [comment]
小白入手分析批量添加群好友难吗

**Comment by lorki** [comment]
> 
> 
> 小白入手分析批量添加群好友难吗

i don't know how to answer this question.
