### ISSUE TITLE
关于消息超过200字符崩溃原因

### ISSUE THREAD

**Issue by chunchunc** [TonyChen56/WeChatRobot#17]
我想请教下为什么在字符限制200以内不会崩溃，这个有什么解决办法吗，能不能在发送消息之前对消息进行切片处理发送，之前主要在web编程，windows编程不太熟悉，还望请教下-.-

**Comment by lorki** [comment]
pls change the buffer size.

**Comment by chunchunc** [comment]
> 请更改缓冲区大小。

具体在哪更改呢

**Comment by chunchunc** [comment]
> 请更改缓冲区大小。
找到了 谢谢

**Comment by chunchunc** [comment]
> > 请更改缓冲区大小。
> 
> 具体在哪更改

> 请更改缓冲区大小。

我现在尝试下

**Comment by chunchunc** [comment]
> pls change the buffer size.

ok,问题解决，感谢

**Comment by 625781186** [comment]
@chunchunc 请问在哪里修改 ， 碰到了一样的问题
