### ISSUE TITLE
WeChatHelper的Release和Debug属性配置问题

### ISSUE THREAD

**Issue by Yang0630** [TonyChen56/WeChatRobot#19]
WeChatHelper Debug生成x86 dll功能一切正常。改成Release生成dll注入后闪退 报错很多问题

**Comment by lorki** [comment]
pls change the platform to x86.

**Comment by Yang0630** [comment]
是x86.但是Release生成的dll就会出现注入崩溃，功能异常。我调整 了Release属性的c++生成不优化，不崩溃了，但是功能不正常了
