### ISSUE TITLE
添加群成员功能好像不能用？

### ISSUE THREAD

**Issue by xuhang2015** [TonyChen56/WeChatRobot#20]
添加群成员功能不能用，直接变成向群里分享成员。
![捕获](https://user-images.githubusercontent.com/10968705/63682751-329fe780-c82b-11e9-99ee-58c8672979d1.PNG)

**Comment by imlinhanchao** [comment]
看看源码，里面少了一个break;

**Comment by TonyChen56** [comment]
哈哈哈 感谢老哥修的bug

**Comment by xuhang2015** [comment]
明白了 感谢两位回复

**Comment by imlinhanchao** [comment]
> 哈哈哈 感谢老哥修的bug

群超過100人的話，試了會拉不進去。還在研究你博客的教程😀
