### ISSUE TITLE
你好，调试用的工具和软件可以分享一下吗？（jiack）

### ISSUE THREAD

**Issue by linyinmobayu** [TonyChen56/WeChatRobot#23]

**Comment by TonyChen56** [comment]
点击链接加入群聊【鬼手PC逆向交流】：https://jq.qq.com/?_wv=1027&k=5AwN6A9

**Comment by linyinmobayu** [comment]
谢谢

鬼手 <notifications@github.com> 于2019年8月29日周四 下午3:20写道：
