### ISSUE TITLE
如果本机昵称过长会显示乱码

### ISSUE THREAD

**Issue by CDandDJ** [TonyChen56/WeChatRobot#25]

**Comment by lorki** [comment]
pls try to change the buffer size!

**Comment by lorki** [comment]
pls try to modify the buffer size!

**Comment by CDandDJ** [comment]
修改了大小依然是这样的------------------ 原始邮件 ------------------
发件人: "Cato <: Love the world and myself."<notifications@github.com>
发送时间: 2019年8月30日(星期五) 晚上9:26
收件人: "TonyChen56/WeChatRobot"<WeChatRobot@noreply.github.com>;
抄送: "Zhangyh"<1565145651@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [TonyChen56/WeChatRobot] 如果本机昵称过长会显示乱码 (#25)



pls try to change the buffer size!
 
&mdash;
