### ISSUE TITLE
这个推广的不错，有话说

### ISSUE THREAD

**Issue by wangshiyu777** [TonyChen56/WeChatRobot#27]
这个推广的不错，有用了成功的老铁吗？交流一下

**Comment by codeByDog** [comment]
新版本开源地址： [https://github.com/codeByDog/pcWechat](url) （将持续不断更新，且用不收费）
![鬼手不要脸](https://user-images.githubusercontent.com/49958949/70022208-6038c180-15ce-11ea-8aa3-a59d8debd67b.png)
