### ISSUE TITLE
WeChatRobot.sln 在win10上面运行之后一点击显示二维码crash

### ISSUE THREAD

**Issue by wheying** [TonyChen56/WeChatRobot#32]
WeChatRobot.sln 在win10上面运行之后一点击显示二维码crash

已经安装了Desktop c++ 2017.

成品可以跑没有问题，感觉应该是源码哪里需要设置啥，感谢作者大大的分享。盼作者大大能解决这个问题，我是windows小白。。。。

**Comment by Amoswish** [comment]
我也遇到这个问题了，你需要把 WeChatHelper.dll 放在自己生成的exe的文件夹下

**Comment by LLoyou00** [comment]
@Amoswish 我这样做了。。但是没有用。。。用 Spy++ 查看确实也没有注入成功。。

**Comment by PeterFuscan** [comment]
Exception thrown at 0x00007FFCB3C83C01 (mfc140ud.dll) in WeChatRobot.exe: 0xC0000005: Access violation reading location 0x0000000000000040.

**Comment by PeterFuscan** [comment]
我放了WeChatHelper.dll以后跳出来这个。。。。然后直接卡死

**Comment by LLoyou00** [comment]
用 VS 打开源代码编译运行，获取二维码 crash 解决方案
1.把  WeChatHelper.dll  这个文件拷贝到 "源码\WeChatRobot\WeChatRobot" 这个目录下面
2.![image](https://user-images.githubusercontent.com/9455777/65670220-821a4300-e077-11e9-8ca8-3d1e7b246d11.png)  这里一定要选 x86 （因为微信客户端是 32 位）

**Comment by PeterFuscan** [comment]
谢啦，刚刚试了能运行了，原来是系统位数的问题

**Comment by chenyongtt** [comment]
请教个问题 ，我也是遇到点击显示二维码  直接就死掉了， 选择的是X86   ， WeChatHelper.dll 也拷贝了， 但为啥还是直接挂了呢  ，还有什么没有到位的吗？

**Comment by chenyongtt** [comment]
可以了， 是我dll位置没放对
