### ISSUE TITLE
期望增加API接口通信

### ISSUE THREAD

**Issue by mrhanCH** [TonyChen56/WeChatRobot#36]
我在想，能否通过客户端获取到数据后，发送给python或者php之类的程序进行解析使用？这样就更加扩大了项目的拓展性。

**Comment by TonyChen56** [comment]
拿我的个人成果和业余时间给你谋私利？还增加项目扩展性？说的这么好听？

**Comment by mrhanCH** [comment]
谋私利？？？首先我没有抨击你的个人成果，也没有强求你的业余时间。我的提问只是出于未知所以才咨询你，我没接触过C++，所以才咨询你能否数据互通，虚心请教学习，然而却得到这样的回复。真不知道你从哪里看出来给我谋私利的？？？
我只是作为一个业余爱好者，对开发者赋予更强大的功能上的期望。不要把每个人都想的那么私利好么，也是醉了。。。

**Comment by impig33** [comment]
能通信才有实际用途，不然只是个简单的自动聊天没多大实用价值。

希望能出api，比如生成http请求啥的，谢谢
