### ISSUE TITLE
手机号查询是只能本人的吗

### ISSUE THREAD

**Issue by lovecuey** [TonyChen56/WeChatRobot#38]
软件闪退,我试了ce查看,只发现了自己的,查询别人的微信没有绿色的Address

**Comment by codeByDog** [comment]
新版本开源地址： [https://github.com/codeByDog/pcWechat](url) （将持续不断更新，且用不收费）
![鬼手不要脸](https://user-images.githubusercontent.com/49958949/70022197-52833c00-15ce-11ea-955e-222b342a3585.png)
