### ISSUE TITLE
能说下怎么编译运行的吗？

### ISSUE THREAD

**Issue by JakeWoki** [TonyChen56/WeChatRobot#43]
没用纯C++开发过项目，能说下环境，怎么编译运行的吗？

**Comment by codeByDog** [comment]
新版本开源地址：[https://github.com/codeByDog/pcWechat  （将持续不断更新，且用不收费）
![鬼手不要脸](https://user-images.githubusercontent.com/49958949/70022172-37b0c780-15ce-11ea-88ae-fef6dfe5fde4.png)
