### ISSUE TITLE
大佬还会出2.7版本的吗

### ISSUE THREAD

**Issue by Hachiko123456** [TonyChen56/WeChatRobot#44]

**Comment by codeByDog** [comment]
新版本开源地址：[https://github.com/codeByDog/pcWechat
![鬼手不要脸](https://user-images.githubusercontent.com/49958949/70022119-ff10ee00-15cd-11ea-944f-aec47c3f8087.png)
](url)

**Comment by impig33** [comment]
这个开发者人品极差，加了他的群，问了一句话他就开始骂人，想要钱你可以说多少，我买的起就买，买不起滚蛋，何必张嘴就咬人? 没这个耐性，就不要在网上甩qq群，为人处事明显拉低中国人形象。
