### ISSUE TITLE
这软件现在还能用吗?

### ISSUE THREAD

**Issue by coder2008** [TonyChen56/WeChatRobot#50]
这软件现在还能用吗?

**Comment by wuchengfei** [comment]
好久没用过了

发送自 Windows 10 版邮件应用

发件人: coder2008
发送时间: 2020年3月20日 14:49
收件人: TonyChen56/WeChatRobot
抄送: Subscribed
主题: [TonyChen56/WeChatRobot] 这软件现在还能用吗? (#50)

这软件现在还能用吗?

**Comment by xujian1998** [comment]
没用▽------------------ 原始邮件 ------------------
发件人: "coder2008"<notifications@github.com>
发送时间: 2020年3月20日(星期五) 下午2:49
收件人: "TonyChen56/WeChatRobot"<WeChatRobot@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [TonyChen56/WeChatRobot] 这软件现在还能用吗? (#50)




 
这软&#x4EF6;现在还能用吗?
 
&mdash;

**Comment by jueban** [comment]
刚使用了一下可以！作者群里更新了微信PC2.8的了

**Comment by coder2008** [comment]
> 刚使用了一下可以！作者群里更新了微信PC2.8的了

哪个群,能把群发一下吗,我的qq:61692460
