### ISSUE TITLE
引发了未经处理的异常:读取访问权限冲突。 pWnd 是 nullptr。

### ISSUE THREAD

**Issue by shuidaan** [TonyChen56/WeChatRobot#58]
引发了异常: 读取访问权限冲突。
**pWnd** 是 nullptr。 出现了 .

_AFXWIN_INLINE LRESULT CWnd::_AFX_FUNCNAME(SendMessage)(UINT message, WPARAM wParam, LPARAM lParam) const
	{ ASSERT(::IsWindow(m_hWnd)); return ::SendMessage(m_hWnd, message, wParam, lParam); }   //此段代码
#pragma push_macro("SendMessage")
#undef SendMessage

**Comment by hancunchou** [comment]
感谢作者，此问题编译配置改成X86就可以了
![image](https://user-images.githubusercontent.com/34182993/93016726-f9811380-f5f5-11ea-8011-55b731305832.png)

**Comment by aohanhongzhi** [comment]
我使用的是VS2022版本,改成x86依然是这样的。
![image](https://user-images.githubusercontent.com/37319319/197385314-6aba501a-0478-48fe-ae9e-baf6a9cf73ee.png)

**Comment by Ruomio** [comment]
> 我使用的是VS2022版本,改成x86依然是这样的。 ![image](https://user-images.githubusercontent.com/37319319/197385314-6aba501a-0478-48fe-ae9e-baf6a9cf73ee.png)
bro 你解决了吗 遇到同样的问题了，我是从其他项目中摘出来一个模块，关闭的时候会出现这个问题
