### ISSUE TITLE
其他语言能调用 WeChatHelper 吗

### ISSUE THREAD

**Issue by vD1S** [TonyChen56/WeChatRobot#9]
不懂C。

好尴尬

**Comment by TonyChen56** [comment]
时间成本太高 暂时未开放接口

**Comment by vD1S** [comment]
持续关注。
期待开放接口的那一天。

**Comment by qq123zhz** [comment]
> 持续关注。
> 期待开放接口的那一天。

开放接口了，估计会被腾讯封

**Comment by lorki** [comment]
In subsequent development versions, **websocket** or http **rest** api interfaces will be provided.
